baseURL = "https://bounty.show/"
languageCode = "en-us"
title = "Bounty Show"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

[[menu.main]]
    name = "Omnibus"
    url = "https://omnibus.live/"
    weight = 2

[params]
  google_analytics_id = "UA-163506427-1"
  homepage_button_link = '/posts'
  homepage_button_text = 'Read The Posts'
  homepage_intro = 'Bounty Show is a list to share opportunities for promotions.'
  # homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Bounty Show is a list to share opportunities for promotions."
    meta_og_title = "Bounty Show"
    meta_og_type = "website"
    meta_og_url = "https://bounty.show/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Bounty Show is a list to share opportunities for promotions."
    meta_twitter_card = "summary"
    meta_twitter_site = "@FxPlayground"
    meta_twitter_creator = "@FxPlayground"

  [params.logo]
      # mobile = "/images/logo-mobile.svg"
      # standard  = "/images/logo.svg"
